  # name
  # This is a GitHub Actions workflow file that defines a workflow named "Greeting Workflow". 
  name: Deploy React to github pages
  on: 
    push:
      branches: 
        - main
        - feature/**
      paths-ignore:
        - '.github/workflows/*'
        - README.md
    workflow_dispatch: # This allows the workflow to be manually triggered from the GitHub Actions tab in the repository. 
  
  jobs:
      test: # Define a job named "greet"
          # Specify the operating system for the job
          runs-on: ubuntu-latest
          steps: # Define the steps for the job
              - name: Get Code
                uses: actions/checkout@v4
              - name: Install Nodejs
                uses: actions/setup-node@v4
                with: 
                  node-version: '20'
              - name: Cache dependencies
                uses: actions/cache@v4
                with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}    
              - name: Install dependencies
                run: npm ci

      build: 
          needs: test
          runs-on: ubuntu-latest
          steps: # Define the steps for the job
              - name: Get Code
                uses: actions/checkout@v4
              - name: Install Nodejs
                uses: actions/setup-node@v4
                with: 
                  node-version: '20'
              - name: Cache dependencies
                uses: actions/cache@v4
                with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}    
              - name: Install dependencies
                run: npm ci

              - name: Build Project
                run: npm run build
              - name: Upload Artifact
                uses: actions/upload-pages-artifact@v4
                with: # Define the name and path of athe artifact to be uploaded
                  name: github-pages # The name of the artifact that will be displayed in the GitHub Actions UI.
                  path: dist # The path to the files or directories that you want to include in the artifact. In this case, it is the "dist" directory, which typically contains the built files of a project.

      # wee the artifact that is is generated in the test  and use it in the deploy job

      deploy: # Define a job named "greet"
          needs: build # This job depends on the "test" job, meaning it will only run if the "test" job completes successfully.
          # Specify the operating system for the job


          
          # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
          permissions:
            pages: write      # to deploy to Pages
            id-token: write   # to verify the deployment originates from an appropriate source

          # Deploy to the github-pages environment
          environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

          # Specify runner + deployment step
          runs-on: ubuntu-latest
          steps:
          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v4 # or specific "vX.X.X" version tag for this action
            with:
              # The path to the directory containing the static files to be deployed. 
              # In this case, it is the "dist" directory, which typically contains the built files of a project.
              token: ${{ secrets.GITHUB_TOKEN }}
              
      